@AuthServer_HostAddress = http://localhost:5000

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MGMxM2NiOC03NzY2LTQ4MWQtYTg2MC0yZTIyNzQ0ODNmMDMiLCJlbWFpbCI6InRlc3RlNEBlbWFpbC5jb20iLCJleHAiOjE3NDA2NzY2NzB9.FuM5dbrxD8Rn7DHfu11hrzCMktLjnCYR5C0NS7CeT10

GET {{AuthServer_HostAddress}}/api/test/
Accept: application/json

###
POST {{AuthServer_HostAddress}}/api/auth/register/
Content-Type: application/json

{
    "email":"teste4@email.com",
    "password":"Senha123!"
}



###
POST {{AuthServer_HostAddress}}/api/auth/login/
Content-Type: application/json

{
    "email":"teste4@email.com",
    "password":"Senha123!"
}



###
GET {{AuthServer_HostAddress}}/api/testeauth/
Authorization: {{token}}
